=pod

=head1 NAME

DateTime::Format::ISO8601 - Parses ISO8601 formats

=head1 SYNOPSIS

    use DateTime::Format::ISO8601;

    my $dt = DateTime::Format::ISO8601->parse_datetime( $str );

    or

    my $dt = DateTime::Format::ISO8601->parse_time( $str );

=head1 DESCRIPTION

Parses almost all ISO8601 date and time formats.

=head1 FORMATS

There are 6 string that can match against date only or time only formats.   The C<parse_datetime> method will attempt to match these ambiguous strings against date only formats.  If you want to match against the time only formats see the C<parse_time> method.

=head2 Conventions

=over 4

=item * Expanded ISO8601

These formats are support with exactly 6 digits for the year.

=item * Precision

If a format doesn't include full precision all larger time unit values are filled in using the current date/time.

=item * Fractional time

There is no limit on the expressed precision.

=back

=head2 Supported via parse_datetime

    YYYYMMDD
    YYYY-MM-DD
    YYYY-MM
    YYYY
    YY
    YYMMDD
    YY-MM-DD
    -YYMM
    -YY-MM
    -YY
    --MMDD
    --MM-DD
    --MM
    ---DD
    +[YY]YYYYMMDD
    +[YY]YYYY-MM-DD
    +[YY]YYYY-MM
    +[YY]YYYY
    +[YY]YY
    YYYYDDD
    YYYY-DDD
    YYDDD
    YY-DDD
    -DDD
    +[YY]YYYYDDD
    +[YY]YYYY-DDD
    YYYYWwwD
    YYYY-Www-D
    YYYYWww
    YYYY-Www
    YYWwwD
    YY-Www-D
    YYWww
    YY-Www
    -YWwwD
    -Y-Www-D
    -YWww
    -Y-Www
    -WwwD
    -Www-D
    -Www
    -W-D
    +[YY]YYYYWwwD
    +[YY]YYYY-Www-D
    +[YY]YYYYWww
    +[YY]YYYY-Www
    hh:mm:ss
    hh:mm
    hhmmss,ss
    hh:mm:ss,ss
    hhmm,mm
    hh:mm,mm
    hh,hh
    -mm:ss
    -mmss,s
    -mm:ss,s
    -mm,m
    --ss,s
    hhmmssZ
    hh:mm:ssZ
    hhmmZ
    hh:mmZ
    hhZ
    hhmmss[+-]hhmm
    hh:mm:ss[+-]hh:mm
    hhmmss[+-]hh
    hh:mm:ss[+-]hh
    YYYYMMDDThhmmss
    YYYY-MM-DDThh:mm:ss
    YYYYMMDDThhmmssZ
    YYYY-MM-DDThh:mm:ssZ
    YYYYMMDDThhmmss[+-]hhmm
    YYYY-MM-DDThh:mm:ss[+-]hh:mm
    YYYYMMDDThhmmss[+-]hh
    YYYY-MM-DDThh:mm:ss[+-]hh
    YYYYMMDDThhmm
    YYYY-MM-DDThh:mm
    YYYYDDDThhmmZ
    YYYY-DDDThh:mmZ
    YYYYWwwDThhmm[+-]hhmm
    YYYY-Www-DThh:mm[+-]hh

=head2 Supported via parse_time

    hhmmss
    hhmm
    hh
    -mmss
    -mm
    --ss

=head1 CREDITS
 
Everyone at the DateTime C<Asylum>.

=head1 AUTHOR
 
Joshua Hoblitt <jhoblitt@cpan.org>
 
=head1 COPYRIGHT
 
Copyright (c) 2003 Joshua Hoblitt.  All rights reserved.  This program
is free software; you can redistribute it and/or modify it under the
same terms as Perl itself.
 
The full text of the license can be found in the LICENSE file included
with this module.
 
=head1 SEE ALSO
 
datetime@perl.org mailing list
 
http://datetime.perl.org/
 
=cut
